class AppStrings {
  AppStrings._();

  static const String appName = 'Darzi Pro';
  static const String tagline = 'Tailor Shop Management System';
  static const String version = 'Version 1.0.0';
  static const String copyright = '© 2026 Darzi Pro. All rights reserved.';

  // Auth
  static const String login = 'Login';
  static const String signIn = 'Sign in to manage your shop';
  static const String phoneOrEmail = 'Phone Number or Email';
  static const String password = 'Password';
  static const String forgotPassword = 'Forgot Password?';
  static const String biometric = 'Biometric';
  static const String orLoginWith = 'or login with';
  static const String secureNote =
      'Securely access your shop records with\nenterprise-grade encryption.';

  // Navigation
  static const String dashboard = 'Dashboard';
  static const String clients = 'Clients';
  static const String orders = 'Orders';
  static const String measurements = 'Measurements';
  static const String tokenCard = 'Token Card';
  static const String reports = 'Reports';
  static const String reminders = 'Reminders';
  static const String settings = 'Settings';

  // Dashboard
  static const String welcomeBack = 'Welcome Back';
  static const String dailyRevenue = 'Daily Revenue';
  static const String monthlyRevenue = 'Monthly Revenue';
  static const String overview = 'Overview';
  static const String totalOrders = 'Total Orders';
  static const String pending = 'Pending';
  static const String ready = 'Ready';
  static const String income = 'Income';
  static const String urgentOrders = 'Urgent Orders';
  static const String deliveryDueToday = 'Delivery due today';
  static const String recentClients = 'Recent Clients';
  static const String viewAll = 'VIEW ALL';
  static const String newClient = 'New Client';
  static const String newOrder = 'New Order';

  // Clients
  static const String searchCustomer = 'Search by name or phone…';
  static const String all = 'All';
  static const String men = 'Men';
  static const String women = 'Women';
  static const String children = 'Children';
  static const String addClient = 'Add Client';
  static const String editClient = 'Edit Client';
  static const String fullName = 'Full Name';
  static const String phone = 'Phone';
  static const String address = 'Address';
  static const String gender = 'Gender';
  static const String notes = 'Notes';
  static const String profile = 'Profile';
  static const String orderHistory = 'Orders';
  static const String save = 'Save';
  static const String cancel = 'Cancel';
  static const String delete = 'Delete';
  static const String back = '← Back';

  // Orders
  static const String allOrders = 'All';
  static const String cutting = 'Cutting';
  static const String stitching = 'Stitching';
  static const String delivered = 'Delivered';
  static const String cancelled = 'Cancelled';
  static const String dressType = 'Dress Type';
  static const String quantity = 'Quantity';
  static const String clothDetails = 'Cloth Details';
  static const String designDetails = 'Design Details';
  static const String unitPrice = 'Unit Price';
  static const String totalAmount = 'Total Amount';
  static const String advancePaid = 'Advance Paid';
  static const String remaining = 'Remaining';
  static const String fullyPaid = 'Fully Paid ✓';
  static const String deliveryDate = 'Delivery Date';
  static const String orderDate = 'Order Date';
  static const String orderNo = 'Order No.';
  static const String token = 'Token';

  // Measurements
  static const String naapCard = 'Naap Card';
  static const String autoFilled = 'Auto-filled from last visit';
  static const String kameez = 'Kameez (Shirt)';
  static const String sleeve = 'Sleeve (Baazoo)';
  static const String shalwar = 'Shalwar (Trousers)';
  static const String customField = '+ Custom Field';

  // Measurement labels (Urdu)
  static const String lambai = 'Lambai';
  static const String chaati = 'Chaati';
  static const String kamar = 'Kamar';
  static const String gardan = 'Gardan';
  static const String baghal = 'Baghal';
  static const String shoulder = 'Shoulder';
  static const String chaurai = 'Chaurai';
  static const String mohri = 'Mohri';
  static const String pauncha = 'Pauncha';
  static const String hip = 'Hip';
  static const String ran = 'Ran (Thigh)';

  // Token Card
  static const String cardPreview = 'Card Preview';
  static const String a4Print = 'A4 Print';
  static const String thermal = 'Thermal';
  static const String whatsapp = 'WhatsApp';
  static const String pdf = 'PDF';
  static const String generatedBy = 'Generated by Darzi Pro';

  // Reports
  static const String reportsTitle = 'Reports';
  static const String today = 'Today';
  static const String thisMonth = 'This Month';
  static const String lastMonth = 'Last Month';
  static const String custom = 'Custom';
  static const String export = '⬇ Export';
  static const String revenue = 'Revenue';
  static const String newOrders = 'New Orders';
  static const String newClients = 'New Clients';
  static const String weeklyRevenueTrend = 'Weekly Revenue Trend';
  static const String last7Days = 'Last 7 days';
  static const String topDressTypes = 'Top Dress Types';

  // Currency
  static const String pkr = 'PKR';
  static const String rsSymbol = '₨';
}
